import json, os
from pathlib import Path
from playwright.sync_api import sync_playwright, expect
out=Path(os.environ.get('BLACKOUT_UI_DIR', '/tmp/spark-blackout-ui'))
errors=[]
with sync_playwright() as p:
 browser=p.chromium.launch(headless=True)
 page=browser.new_page(viewport={'width':1440,'height':1100})
 page.on('pageerror',lambda e: errors.append(str(e)))
 page.on('dialog',lambda d: d.accept())
 page.goto(os.environ.get('BLACKOUT_UI_URL', 'http://127.0.0.1:4173'),wait_until='networkidle')
 expect(page.get_by_text('등록된 차단 기간이 없습니다.',exact=False)).to_be_visible()
 page.get_by_label('차단 시작일').fill('2099-01-10')
 page.get_by_label('차단 종료일').fill('2099-01-12')
 page.get_by_label('회원 안내 문구').fill('브라우저 검증용 연휴')
 page.get_by_role('button',name='영향 확인 후 저장').click()
 expect(page.get_by_text('기존 미보관 작업:',exact=False)).to_be_visible()
 assert page.evaluate('window.fixtureRules.length')==0
 page.get_by_role('button',name='설정 저장',exact=True).click()
 expect(page.get_by_text('시작일 접수 제한을 저장했습니다.',exact=False)).to_be_visible()
 expect(page.get_by_text('사용 중',exact=True)).to_be_visible()
 assert page.evaluate('window.fixtureRules.length')==1
 page.screenshot(path=str(out/'admin-settings.png'),full_page=True)
 page.get_by_role('button',name='calendar',exact=True).click()
 expect(page.get_by_text('모든 프로그램 공통',exact=False)).to_be_visible()
 page.get_by_role('button',name='시작일 달력 열기').click()
 for date in ['2099-01-10','2099-01-11','2099-01-12']: expect(page.get_by_role('button',name=date,exact=True)).to_be_disabled()
 expect(page.get_by_role('button',name='2099-01-13',exact=True)).to_be_enabled()
 page.get_by_role('button',name='2099-01-13',exact=True).click()
 expect(page.get_by_role('textbox',name='시작일',exact=True)).to_have_value('2099-01-13')
 page.get_by_role('textbox',name='시작일',exact=True).fill('2099-01-11')
 expect(page.get_by_role('alert')).to_contain_text('접수 제한 기간')
 page.set_viewport_size({'width':390,'height':844})
 page.get_by_role('button',name='시작일 달력 열기').click()
 page.screenshot(path=str(out/'mobile-calendar.png'),full_page=True)
 assert page.evaluate('document.documentElement.scrollWidth <= innerWidth+1')
 page.set_viewport_size({'width':1440,'height':1100})
 page.get_by_role('button',name='intake',exact=True).click()
 page.locator('input[type=file]').set_input_files(str(out/'member-blocked.xlsx'))
 expect(page.get_by_role('button',name='2건 접수',exact=True)).to_be_disabled()
 expect(page.get_by_text('3행 · 엑셀테스트:',exact=False)).to_be_visible()
 assert page.evaluate('window.fixtureCalls.length')==0
 page.screenshot(path=str(out/'member-excel-blocked.png'),full_page=True)
 page.get_by_role('button',name='취소',exact=True).click()
 page.locator('input[type=file]').set_input_files(str(out/'member-allowed.xlsx'))
 expect(page.get_by_role('button',name='2건 접수',exact=True)).to_be_enabled()
 page.get_by_role('button',name='2건 접수',exact=True).click()
 page.wait_for_function('window.fixtureCalls.length === 1')
 page.get_by_role('button',name='adminExcel',exact=True).click()
 page.locator('input[type=file]').set_input_files(str(out/'admin-blocked.xlsx'))
 expect(page.get_by_text('시작일 제한 오류가 있어 파일을 제출할 수 없습니다.',exact=False)).to_be_visible()
 expect(page.get_by_role('button',name='정상 1건 부여',exact=True)).to_be_disabled()
 page.wait_for_function('window.fixtureCalls.length === 1')
 page.get_by_role('dialog').get_by_role('button',name='닫기',exact=True).first.click()
 page.get_by_role('button',name='edit',exact=True).click()
 page.get_by_label('수정 사유').fill('메모 수정')
 expect(page.get_by_role('button',name='변경 영향 확인',exact=True)).to_be_enabled()
 page.get_by_role('textbox',name='시작일',exact=True).fill('2099-01-11')
 expect(page.get_by_role('button',name='변경 영향 확인',exact=True)).to_be_disabled()
 page.get_by_role('textbox',name='시작일',exact=True).fill('2099-01-10')
 expect(page.get_by_role('button',name='변경 영향 확인',exact=True)).to_be_enabled()
 page.get_by_role('button',name='취소',exact=True).click()
 page.get_by_role('button',name='calendar',exact=True).click()
 page.evaluate("window.fixtureFailure=true; window.dispatchEvent(new Event('spark-start-date-restrictions-changed'))")
 expect(page.get_by_text('테스트 연결 오류',exact=False)).to_be_visible()
 page.get_by_role('button',name='시작일 달력 열기').click()
 expect(page.get_by_role('button',name='2099-01-13',exact=True)).to_be_disabled()
 page.evaluate("window.fixtureFailure=false; window.dispatchEvent(new Event('spark-start-date-restrictions-changed'))")
 expect(page.get_by_role('button',name='2099-01-13',exact=True)).to_be_enabled()
 assert not errors,errors
 result={'admin_save_and_impact':True,'inclusive_calendar_disabled':True,'mobile_390_no_overflow':True,'member_excel_blocked_and_allowed':True,'admin_excel_blocked':True,'unchanged_date_edit_allowed':True,'fail_closed_and_recovery':True,'page_errors':errors,'environment':'isolated Chromium, mocked Supabase; no production mutation'}
 (out/'result.json').write_text(json.dumps(result,ensure_ascii=False,indent=2))
 print(json.dumps(result,ensure_ascii=False,indent=2))
 browser.close()
